<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->tag->getTitle() ?>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    
	
	
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	
	<?php $this->assets->outputCss('css'); ?>
	

	<!-- Font Awesome -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    
  </head>
  <!-- ADD THE CLASS layout-top-nav TO REMOVE THE SIDEBAR. -->
  <body class="hold-transition skin-blue sidebar-mini">


<a href="" class=""></a>
    <div class="wrapper">
		<header class="main-header">
			<!-- Logo -->
			<a href="index2.html" class="logo">
			  <!-- mini logo for sidebar mini 50x50 pixels -->
			  <span class="logo-mini"><b>IATI</b></span>
			  <!-- logo for regular state and mobile devices -->
			  <span class="logo-lg"><small><!-- MIS6020 --></small><b> IATI</b> Viewer</span>
			</a>

			<nav class="navbar navbar-static-top" role="navigation">
				<!-- Sidebar toggle button-->
				<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
					<span class="sr-only">Toggle navigation</span>
				</a>
			</nav>
		</header>
		<aside class="main-sidebar">

			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">

				<!-- Sidebar user panel (optional) -->
				<div class="user-panel">
					<div class="pull-left image">
						<img src="<?= @$user_avator ?>" class="" alt="User Image">
					</div>
					<div class="pull-left info">
					<p><?= @$username; ?></p>
					<!-- Status -->
					<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
					</div>
				</div>

				<!-- Sidebar Menu -->
				<ul class="sidebar-menu">
					<?= @$sidebar; ?>
				</ul><!-- /.sidebar-menu -->
			</section>
			<!-- /.sidebar -->
		</aside>
      
      
	  <!-- Full Width Column -->
      <div class="content-wrapper">

		  <!-- Content Header (Page header) -->
          <section class="content-header">
			 
            <h1><?= @$page_header ?>&nbsp;</h1>
            
			<?= @$breadcrumbs ?>

          </section>

            <!-- Main content -->
            <section class="content">
			<div class="row">
				<div class = "col-md-12">
					<div class="box box-default">
					  
					  <div class="box-body">
						
						<?= $this->getContent(); ?>
						
						<?= @$content ?>
						
					  </div><!-- /.box-body -->
					</div><!-- /.box -->
				</div>
            </div>
			
			</section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      
	  
	  <?= @$footer ?>
    
	
	</div><!-- ./wrapper -->

	<?php $this->assets->outputJs('js'); ?>

	<script type="text/javascript">
	<!--
	$(function () {
		PNotify.prototype.options.styling = "bootstrap3";
		PNotify.prototype.options.styling = "fontawesome";
	});
	//-->
	</script>
	

	<?php
	 foreach($javascript as $script)
     {    	
    	print $script ;
     }
	?> 
   

  </body>
</html>
