<?php
	$tenant_and_base_url = $this->session->get("tenant-and-base-url");
?>

<ul class="nav navbar-nav">
<!-- 
<li class="active"><a href="<?= $tenant_and_base_url ?>default/"> Home <span class="sr-only">(current)</span></a></li>
 -->
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Staff <span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
	<li><a href="<?= $tenant_and_base_url ?>staff/add">Add staff</a></li>
	<li><a href="<?= $tenant_and_base_url ?>staff/list">Staff list</a></li>
	<li><a href="<?= $tenant_and_base_url ?>staff/grouped-list">Staff grouped list</a></li>

	<li><a href="<?= $tenant_and_base_url ?>staff/advance-search">Advance staff search</a></li>
  </ul>
</li>

<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Entity <span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
	<!-- ><li><a href="<?= $tenant_and_base_url ?>office/add">Add office</a></li>
	<li><a href="<?= $tenant_and_base_url ?>office/list">UNEP office list</a></li>
	<li><a href="<?= $tenant_and_base_url ?>office/map">UNEP office map</a></li>
	<li class="divider"></li>
	<li><a href="#"><strong>Entity</strong></a></li> 
	<li><a href="<?= $tenant_and_base_url ?>entity/add"> Add entity</a></li> -->
	<li><a href="<?= $tenant_and_base_url ?>entity"> List entities</a></li>
  </ul>
</li>

<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Administration <span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
	<li><a href="#"><strong>UNEP Cities</strong></a></li>
	<li><a href="<?= $tenant_and_base_url ?>city/add"> Add city</a></li>
	<li><a href="<?= $tenant_and_base_url ?>office/list"> List cities</a></li>
	<li class="divider"></li>
	<li><a href="#"><strong>Contract types</strong></a></li>
	<li><a href="<?= $tenant_and_base_url ?>contract-type/add"> Add contract type</a></li>
	<li><a href="<?= $tenant_and_base_url ?>contract-type/list"> List contract types</a></li>	
  </ul>
</li>

<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Role Management <span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
	<li><a href="#"><strong>Roles</strong></a></li>
	<li><a href="<?= $tenant_and_base_url ?>role/add"> New role</a></li>
	<li><a href="<?= $tenant_and_base_url ?>role/list"> List roles</a></li>
	<li class="divider"></li>
	<li><a href="#"><strong>Staff Roles</strong></a></li>
	<li><a href="<?= $tenant_and_base_url ?>role/asign-to-staff"> Assign role to staff</a></li>
  </ul>
</li>
</ul>
