<!-- Messages: style can be found in dropdown.less-->
  <li class="dropdown messages-menu">
	<!-- Menu toggle button -->
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	  <i class="fa fa-envelope-o"></i>
	  <span class="label <?= $messages_count > 0 ? 'label-success' : '' ?>"> <?= $messages_count ?> </span>
	</a>
	<ul class="dropdown-menu">
	  <li class="header">You have <?= $messages_count ?> messages</li>
	  <li>
		<!-- inner menu: contains the messages -->
				
		<ul class="menu">
		  
		  <?php foreach($messages AS $message) : ?>

		  <li><!-- start message -->
			<a href="#">
			  <div class="pull-left">
				<!-- User Image -->
				<img src="<?= $user_avator ?>" class="img-circle" alt="User Image">
			  </div>
			  <!-- Message title and timestamp -->
			  <h4>
				<?= $message['subject'] ?>
				<small><i class="fa fa-clock-o"></i> <?php $message['time_ago'] ?></small>
			  </h4>
			  <!-- The message -->
			  <p><?= $message['body'] ?></p>
			</a>
		  </li><!-- end message -->

		  <?php endforeach ; ?>
		
		</ul><!-- /.menu -->
	  
	  </li>
	  <li class="footer"><a href="#">See All Messages</a></li>
	</ul>
  </li><!-- /.messages-menu -->