    <!-- Notifications Menu -->
  <li class="dropdown notifications-menu">
	<!-- Menu toggle button -->
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	  <i class="fa fa-bell-o"></i>
	  <span class="label <?= $notifications_count > 0 ? 'label-warning' : '' ?>"><?= $notifications_count ?></span>
	</a>
	<ul class="dropdown-menu">
	  <li class="header">You have <?= $notifications_count ?> notifications</li>
	  <li>
		<!-- Inner Menu: contains the notifications -->
		<ul class="menu">

			<?php foreach($notifications AS $notification ) : ?>

			  <li><!-- start notification -->
				<a href="#">
				  <i class="fa <?= $notification['icon'] ?> text-aqua"></i> <?= $notification['body'] ?>
				</a>
			  </li><!-- end notification -->
			
			<?php endforeach ; ?>

		</ul>
	  </li>
	  <li class="footer"><a href="#">View all</a></li>
	</ul>
  </li>