  <!-- User Account Menu -->
  <li class="dropdown user user-menu">
	<!-- Menu Toggle Button -->
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	  <!-- The user image in the navbar-->
	  <img src="<?= @$user_avator ?>" class="user-image" alt="User Image">
	  <!-- hidden-xs hides the username on small devices so only the image appears. -->
	  <span class="hidden-xs"><?= @$user_names ?></span>
	</a>
	<ul class="dropdown-menu">
	  <!-- The user image in the menu -->
	  <li class="user-header">
		<img src="<?= @$user_avator ?>" class="img-circle" alt="User Image">
		<p>
		  <?= $user_names ?>
		  <small><?= @$member_since ?></small>
		</p>
	  </li>
	  <!-- Menu Body -->
	  
	  <!-- <li class="user-body">
		<div class="col-xs-4 text-center">
		  <a href="#">Followers</a>
		</div>
		<div class="col-xs-4 text-center">
		  <a href="#">Sales</a>
		</div>
		<div class="col-xs-4 text-center">
		  <a href="#">Friends</a>
		</div>
	  </li> -->

	  <!-- Menu Footer-->
	  <li class="user-footer">
		<div class="pull-left">
		  <a href="#" class="btn btn-default btn-flat">Profile</a>
		</div>
		<div class="pull-right">
		  <a href="#" class="btn btn-default btn-flat">Sign out</a>
		</div>
	  </li>
	</ul>
  </li>