<div class="row" id="data-holder">

<div class="col-md-12">

<div class="box">
            <div class="box-header with-border">
              <!-- <h3 class="box-title">Activity file: </h3> -->

			  

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <div class="btn-group">
                  <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-wrench"></i></button>
                  <!-- <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                  </ul> -->
                </div>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>

				<div class="row">
			  
				  <label for="org_id" class="col-sm-1 col-md-1 control-label">Organizations</label>
					
				  <div class="col-sm-4 col-md-4">
				  <select style="width:100%;" id="org_id">
					
				  </select>
				  </div>
				 

				 <label for="country_iso2" class="col-sm-1 col-md-1 control-label">Countries</label>
					<div class="col-sm-4 col-md-4">
				  <select style="width:100%;" id="country_iso2"></select>
				  </div>
				
				</div>

				<div class="row" style="margin-top:15px;">

				 <label for="activity_file_id" class="col-sm-1 col-md-1 control-label">Activity&nbsp;Files</label>
				 <div class="col-sm-4 col-md-4">
				 <select style="width:100%;" id="activity_file_id"></select>
				 </div>

				<label for="transaction_code" class="col-sm-1 col-md-1 control-label">Trxn&nbsp;type</label>
				<div class="col-sm-3 col-md-3">
				 <select style="width:100%;" id="transaction_code"></select>
				</div>

				 <div class="col-sm-1 col-md-1">
				  <button type="button" id="btn-map-it" class="btn btn-success"><i style="font-size:0.9em;" class="fa fa-globe"> map</i></button>
				 </div>

			  </div>
			 


            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="row">
                <div class="col-md-10">

				   <div style="margin-top:15px;">              
					<div id="map" style="min-height:420px;"></div>
				   </div>

                  <!-- /.chart-responsive -->
                </div>
                <!-- /.col -->
                <div class="col-md-2">

				 <div id="additional-info" >
				 </div>
                  

				</div>
                <!-- /.col -->


              </div>
              <!-- /.row -->
            </div>
            <!-- ./box-body -->
            <div class="box-footer">
              <div class="row" id="gdp-row">


                
				


              </div>
              <!-- /.row -->
            </div>
            <!-- /.box-footer -->
          </div>

</div>
</div>