<div class="row">



<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
	<span class="info-box-icon bg-green"><i class="fa fa-sitemap" aria-hidden="true"></i>
	</span>

	<div class="info-box-content">
	  <span class="info-box-text">Organizations</span>
	  <span class="info-box-number"><?= $data['org_cnt'] ?></span>
	</div>
	<!-- /.info-box-content -->
  </div>
  <!-- /.info-box -->
</div>
<!-- /.col -->


<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
	<span class="info-box-icon bg-aqua"><i class="ion ion-arrow-graph-up-right"></i></span>

	<div class="info-box-content">
	  <span class="info-box-text">Activities</span>
	  <span class="info-box-number"><?= $data['actv_cnt'] ?></span>
	</div>
	<!-- /.info-box-content -->
  </div>
  <!-- /.info-box -->
</div>
<!-- /.col -->

<!-- fix for small devices only -->
<div class="clearfix visible-sm-block"></div>


<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
	<span class="info-box-icon bg-red"><i class="ion ion-earth" aria-hidden="true"></i></span>

	<div class="info-box-content">
	  <span class="info-box-text">Countries</span>
	  <span class="info-box-number"><?= $data['ctry_cnt'] ?></span>
	</div>
	<!-- /.info-box-content -->
  </div>
  <!-- /.info-box -->
</div>
<!-- /.col -->


<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="info-box">
	<span class="info-box-icon bg-yellow"><i class="fa fa-money" aria-hidden="true"></i></span>

	<div class="info-box-content">
	  <span class="info-box-text">Total Spent</span>
	  <span class="info-box-number">2,000</span>
	</div>
	<!-- /.info-box-content -->
  </div>
  <!-- /.info-box -->
</div>
<!-- /.col -->
</div>